import type { Metadata } from "next"
import "@/globals.css"
import MenuBar, { MenuBarLink } from "@/components/design_system/structure/menu_bar"
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}
import { PageHeader } from "@/components/design_system/structure/page_header"

export const links: MenuBarLink[] = [
  { href: "/design_system", label: "Home" },
  { href: "/design_system/list", label: "List" },
  { href: "/design_system/layout", label: "Layout" },
  { href: "/design_system/tabs", label: "Tabs" },
  { href: "/design_system/form", label: "Form" },
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <div className="flex ml-2 gap-6">
        <div className=" w-[360px] "></div>
        <div className="w-full mr-24">
          <div className="flex content-start mb-4">
            <MenuBar links={links} />
          </div>
          <div className="flex content-center mb-4">
            <PageHeader product="wrapper" />
          </div>
          <div>{children}</div>
        </div>
      </div>
    </>
  )
}
