import type { Metadata } from "next"
import "@/css_globals.css"
import MenuBar, { MenuBarLink } from "@/components/design_system/structure/menu_bar"
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}
import { PageHeader } from "@/components/design_system/structure/list_page_header"

export const links: MenuBarLink[] = [
  { href: "/design_system", label: "Home" },
  { href: "/design_system/list", label: "List" },
  { href: "/design_system/layout", label: "Layout" },
  { href: "/design_system/tabs", label: "Tabs" },
  { href: "/design_system/form", label: "Form" },
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <div className="ml-2 flex gap-6">
        <div className="w-[360px]"></div>
        <div className="mr-24 w-full">
          <div className="mb-4 flex content-start">
            <MenuBar links={links} />
          </div>
          <div className="mb-4 flex content-center">
            <PageHeader product="wrapper" />
          </div>
          <div>{children}</div>
        </div>
      </div>
    </>
  )
}
