import { AssetData } from "@/types"
import { TOKEN_ADDR } from "@/services/repo_asset_addresses"

export type AssetConfigKey = keyof typeof TOKEN_ADDR

export const assetConfig: Record<AssetConfigKey, AssetData> = {
  USDC: {
    address: TOKEN_ADDR.USDC,
    symbol: "USDC",
    name: "USD Coin",
    decimals: 6,
    displayDecimals: 2,
    logoKey: "USDC",
  },
  CVX: {
    address: TOKEN_ADDR.CVX,
    symbol: "CVX",
    name: "Convex",
    decimals: 18,
    displayDecimals: 0,
    logoKey: "CVX",
  },
  CRV: {
    address: TOKEN_ADDR.CRV,
    name: "Curve DAO",
    symbol: "CRV",
    decimals: 18,
    displayDecimals: 0,
    logoKey: "CRV",
  },
  FXN: {
    symbol: "FXN",
    name: "FXN Token",
    decimals: 18,
    address: TOKEN_ADDR.FXN,
    displayDecimals: 0,
    logoKey: "FXN",
  },
  BAL: {
    symbol: "BAL",
    name: "Balancer",
    decimals: 18,
    displayDecimals: 0,
    logoKey: "BAL",
    address: TOKEN_ADDR.BAL,
  },
  PENDLE: {
    symbol: "PENDLE",
    name: "Pendle",
    decimals: 18,
    logoKey: "PENDLE",
    address: TOKEN_ADDR.PENDLE,
    displayDecimals: 0,
  },
  CRVUSD: {
    symbol: "crvUSD",
    name: "crvUSD",
    decimals: 18,
    address: TOKEN_ADDR.CRVUSD,
    logoKey: "CRVUSD",
    displayDecimals: 0,
  },
  CVGCVX: {
    symbol: "cvgCVX",
    name: "cvgCVX",
    decimals: 18,
    address: TOKEN_ADDR.CVGCVX,
    displayDecimals: 0,
    logoKey: "CVGCVX",
  },
  CVGSDT: {
    symbol: "cvgSDT",
    name: "cvgSDT",
    decimals: 18,
    address: TOKEN_ADDR.CVGSDT,
    logoKey: "CVGSDT",
    displayDecimals: 0,
  },
  ETH: {
    symbol: "ETH",
    name: "Ethereum",
    decimals: 18,
    displayDecimals: 4,
    address: TOKEN_ADDR.ETH,
    logoKey: "ETH",
  },
  SDT: {
    symbol: "SDT",
    name: "SDT",
    decimals: 18,
    address: TOKEN_ADDR.SDT,
    logoKey: "SDT",
    displayDecimals: 0,
  },
  WETH: {
    symbol: "WETH",
    name: "Wrapped Ether",
    decimals: 18,
    displayDecimals: 4,
    logoKey: "WETH",
    address: TOKEN_ADDR.WETH,
  },
  wstETH: {
    symbol: "wstETH",
    name: "Wrapped liquid staked Ether 2.0",
    decimals: 18,
    address: TOKEN_ADDR.wstETH,
    logoKey: "wstETH",
    displayDecimals: 4,
  },
  TRICRV: {
    symbol: "3CRV",
    name: "Curve.fi DAI/USDC/USDT",
    decimals: 18,
    address: TOKEN_ADDR.TRICRV,
    logoKey: "TRICRV",
    displayDecimals: 2,
  },
  "crvUSD-USDC": {
    symbol: "crvUSD-USDC",
    name: "Curve USD/USDC",
    decimals: 18,
    address: TOKEN_ADDR["crvUSD-USDC"],
    logoKey: "crvUSD-USDC",
    displayDecimals: 2,
  },
  "crvUSD-USDT": {
    symbol: "crvUSD-USDT",
    name: "Curve USD/USDT",
    decimals: 18,
    address: TOKEN_ADDR["crvUSD-USDT"],
    logoKey: "crvUSD-USDT",
    displayDecimals: 2,
  },
  "USDC-fxUSD": {
    symbol: "USDC-fxUSD",
    name: "USDC-fxUSD",
    decimals: 18,
    address: TOKEN_ADDR["USDC-fxUSD"],
    logoKey: "USDC-fxUSD",
    displayDecimals: 2,
  },
  "USDC-USDT": {
    symbol: "USDC-USDT",
    name: "USDC-USDT",
    decimals: 18,
    address: TOKEN_ADDR["USDC-USDT"],
    logoKey: "USDC-USDT",
    displayDecimals: 2,
  },
  "frxUSD-USDe": {
    symbol: "frxUSD-USDe",
    name: "frxUSD-USDe",
    decimals: 18,
    address: TOKEN_ADDR["frxUSD-USDe"],
    logoKey: "frxUSD-USDe",
    displayDecimals: 2,
  },

  "frxETH-WETH": {
    symbol: "frxETH-WETH",
    name: "frxETH-WETH",
    decimals: 18,
    address: TOKEN_ADDR["frxETH-WETH"],
    logoKey: "frxETH-WETH",
    displayDecimals: 2,
  },
  "pxETH-stETH": {
    symbol: "pxETH-stETH",
    name: "pxETH-stETH",
    decimals: 18,
    address: TOKEN_ADDR["pxETH-stETH"],
    logoKey: "pxETH-stETH",
    displayDecimals: 2,
  },
  "pxETH-WETH": {
    symbol: "pxETH-WETH",
    name: "pxETH-WETH",
    decimals: 18,
    address: TOKEN_ADDR["pxETH-WETH"],
    logoKey: "pxETH-WETH",
    displayDecimals: 2,
  },
  "cbBTC-WBTC": {
    symbol: "cbBTC-WBTC",
    name: "cbBTC-WBTC",
    decimals: 18,
    address: TOKEN_ADDR["cbBTC-WBTC"],
    logoKey: "cbBTC-WBTC",
    displayDecimals: 2,
  },
  "crvUSD-ETH-CRV": {
    symbol: "crvUSD-ETH-CRV",
    name: "crvUSD-ETH-CRV",
    decimals: 18,
    address: TOKEN_ADDR["crvUSD-ETH-CRV"],
    logoKey: "crvUSD-ETH-CRV",
    displayDecimals: 2,
  },
  "GHO-cbBTC-WETH": {
    symbol: "GHO-cbBTC-WETH",
    name: "GHO-cbBTC-WETH",
    decimals: 18,
    address: TOKEN_ADDR["GHO-cbBTC-WETH"],
    logoKey: "GHO-cbBTC-WETH",
    displayDecimals: 2,
  },

  "USDC-WBTC-WETH": {
    symbol: "USDC-WBTC-WETH",
    name: "USDC-WBTC-WETH",
    decimals: 18,
    address: TOKEN_ADDR["USDC-WBTC-WETH"],
    logoKey: "USDC-WBTC-WETH",
    displayDecimals: 2,
  },

  "USDT-WBTC-WETH": {
    symbol: "USDT-WBTC-WETH",
    name: "USDT-WBTC-WETH",
    decimals: 18,
    address: TOKEN_ADDR["USDT-WBTC-WETH"],
    logoKey: "USDT-WBTC-WETH",
    displayDecimals: 2,
  },

  "USR-RLP": {
    symbol: "USR-RLP",
    name: "USR-RLP",
    decimals: 18,
    address: TOKEN_ADDR["USR-RLP"],
    logoKey: "USR-RLP",
    displayDecimals: 2,
  },

  "CVX-ETH": {
    symbol: "CVX-ETH",
    name: "CVX-ETH",
    decimals: 18,
    address: TOKEN_ADDR["CVX-ETH"],
    logoKey: "CVX-ETH",
    displayDecimals: 2,
  },
  sUSG: {
    symbol: "sUSG",
    name: "sUSG",
    decimals: 18,
    address: TOKEN_ADDR.sUSG,
    logoKey: "sUSG",
    displayDecimals: 2,
  },
  USG: {
    symbol: "USG",
    name: "USG",
    decimals: 18,
    address: TOKEN_ADDR.USG,
    logoKey: "USG",
    displayDecimals: 2,
  },
  wcrvUSD: {
    symbol: "wcrvUSD",
    name: "wcrvUSD",
    decimals: 18,
    address: TOKEN_ADDR["wcrvUSD"],
    logoKey: "wcrvUSD",
    displayDecimals: 2,
  },
  scrvUSD: {
    symbol: "scrvUSD",
    name: "scrvUSD",
    decimals: 18,
    address: TOKEN_ADDR["scrvUSD"],

    logoKey: "scrvUSD",
    displayDecimals: 2,
  },
  crvUSD: {
    symbol: "crvUSD",
    name: "crvUSD",
    decimals: 18,
    address: TOKEN_ADDR["crvUSD"],
    logoKey: "crvUSD",
    displayDecimals: 2,
  },
  sTAN: {
    symbol: "sTAN",
    name: "sTAN",
    decimals: 18,
    address: TOKEN_ADDR["sTAN"],
    logoKey: "sTAN",
    displayDecimals: 2,
  },
  TAN: {
    symbol: "TAN",
    name: "TAN",
    decimals: 18,
    address: TOKEN_ADDR["TAN"],
    logoKey: "TAN",
    displayDecimals: 2,
  },
  vsTAN: {
    symbol: "vsTAN",
    name: "vsTAN",
    decimals: 18,
    address: TOKEN_ADDR["vsTAN"],
    logoKey: "vsTAN",
    displayDecimals: 2,
  },
  frxUSD: {
    symbol: "frxUSD",
    name: "frxUSD",
    decimals: 18,
    address: TOKEN_ADDR["frxUSD"],
    logoKey: "frxUSD",
    displayDecimals: 2,
  },
  "USG-frxUSD": {
    symbol: "USG-frxUSD",
    name: "USG-frxUSD",
    decimals: 18,
    address: TOKEN_ADDR["USG-frxUSD"],
    logoKey: "USG-frxUSD",
    displayDecimals: 2,
  },
  "USG-USDC": {
    symbol: "USG-USDC",
    name: "USG-USDC",
    decimals: 18,
    address: TOKEN_ADDR["USG-USDC"],
    logoKey: "USG-USDC",
    displayDecimals: 2,
  },
}
