import { AssetData } from "@/types"
import { TOKEN_ADDR } from "@/services/repo_asset_addresses"

export type AssetConfigKey = keyof typeof TOKEN_ADDR

export const assetConfig: Record<AssetConfigKey, AssetData> = {
  USDC: {
    address: TOKEN_ADDR.USDC,
    symbol: "USDC",
    name: "USD Coin",
    decimals: 6,
    displayDecimals: 2,
    logo: "USDC",
  },
  CVX: {
    address: TOKEN_ADDR.CVX,
    symbol: "CVX",
    name: "Convex",
    decimals: 18,
    displayDecimals: 0,
    logo: "CVX",
  },
  CRV: {
    address: TOKEN_ADDR.CRV,
    name: "Curve DAO",
    symbol: "CRV",
    decimals: 18,
    displayDecimals: 0,
    logo: "CRV",
  },
  FXN: {
    symbol: "FXN",
    name: "FXN Token",
    decimals: 18,
    address: TOKEN_ADDR.FXN,
    displayDecimals: 0,
    logo: "FXN",
  },
  BAL: {
    symbol: "BAL",
    name: "Balancer",
    decimals: 18,
    displayDecimals: 0,
    logo: "BAL",
    address: TOKEN_ADDR.BAL,
  },
  PENDLE: {
    symbol: "PENDLE",
    name: "Pendle",
    decimals: 18,
    logo: "PENDLE",
    address: TOKEN_ADDR.PENDLE,
    displayDecimals: 0,
  },
  CRVUSD: {
    symbol: "crvUSD",
    name: "crvUSD",
    decimals: 18,
    address: TOKEN_ADDR.CRVUSD,
    logo: "CRVUSD",
    displayDecimals: 0,
  },
  CVGCVX: {
    symbol: "cvgCVX",
    name: "cvgCVX",
    decimals: 18,
    address: TOKEN_ADDR.CVGCVX,
    displayDecimals: 0,
    logo: "CVGCVX",
  },
  CVGSDT: {
    symbol: "cvgSDT",
    name: "cvgSDT",
    decimals: 18,
    address: TOKEN_ADDR.CVGSDT,
    logo: "CVGSDT",
    displayDecimals: 0,
  },
  ETH: {
    symbol: "ETH",
    name: "Ethereum",
    decimals: 18,
    displayDecimals: 4,
    address: TOKEN_ADDR.ETH,
    logo: "ETH",
  },
  sdBAL: {
    symbol: "sdBAL",
    name: "Stake DAO Balancer",
    decimals: 18,
    displayDecimals: 0,
    address: TOKEN_ADDR.sdBAL,
    logo: "sdBAL",
  },
  sdCRV: {
    symbol: "sdCRV",
    name: "Stake DAO CRV",
    decimals: 18,
    displayDecimals: 0,
    address: TOKEN_ADDR.sdCRV,
    logo: "sdCRV",
  },
  sdFXN: {
    symbol: "sdFXN",
    name: "Stake DAO FXN",
    decimals: 18,
    displayDecimals: 0,
    address: TOKEN_ADDR.sdFXN,
    logo: "sdFXN",
  },
  sdPENDLE: {
    symbol: "sdPENDLE",
    name: "Stake DAO PENDLE",
    decimals: 18,
    address: TOKEN_ADDR.sdPENDLE,
    displayDecimals: 0,
    logo: "sdPENDLE",
  },
  SDT: {
    symbol: "SDT",
    name: "SDT",
    decimals: 18,
    address: TOKEN_ADDR.SDT,
    logo: "SDT",
    displayDecimals: 0,
  },
  WETH: {
    symbol: "WETH",
    name: "Wrapped Ether",
    decimals: 18,
    displayDecimals: 4,
    logo: "WETH",
    address: TOKEN_ADDR.WETH,
  },
  wstETH: {
    symbol: "wstETH",
    name: "Wrapped liquid staked Ether 2.0",
    decimals: 18,
    address: TOKEN_ADDR.wstETH,
    logo: "wstETH",
    displayDecimals: 4,
  },
  BAL80: {
    symbol: "BAL80",
    name: "Balancer Aave Boosted StablePool",
    decimals: 18,
    address: TOKEN_ADDR.BAL80,
    logo: "BAL",
    displayDecimals: 2,
  },
  TRICRV: {
    symbol: "3CRV",
    name: "Curve.fi DAI/USDC/USDT",
    decimals: 18,
    address: TOKEN_ADDR.TRICRV,
    logo: "TRICRV",
    displayDecimals: 2,
  },
  "crvUSD-USDC": {
    symbol: "crvUSD-USDC",
    name: "Curve USD/USDC",
    decimals: 18,
    address: TOKEN_ADDR["crvUSD-USDC"],
    logo: "crvUSD-USDC",
    displayDecimals: 2,
  },
  "crvUSD-USDT": {
    symbol: "crvUSD-USDT",
    name: "Curve USD/USDT",
    decimals: 18,
    address: TOKEN_ADDR["crvUSD-USDT"],
    logo: "crvUSD-USDT",
    displayDecimals: 2,
  },
  "USDC-fxUSD": {
    symbol: "USDC-fxUSD",
    name: "USDC-fxUSD",
    decimals: 18,
    address: TOKEN_ADDR["USDC-fxUSD"],
    logo: "USDC-fxUSD",
    displayDecimals: 2,
  },
  "USDC-USDT": {
    symbol: "USDC-USDT",
    name: "USDC-USDT",
    decimals: 18,
    address: TOKEN_ADDR["USDC-USDT"],
    logo: "USDC-USDT",
    displayDecimals: 2,
  },
  "frxUSD-USDe": {
    symbol: "frxUSD-USDe",
    name: "frxUSD-USDe",
    decimals: 18,
    address: TOKEN_ADDR["frxUSD-USDe"],
    logo: "frxUSD-USDe",
    displayDecimals: 2,
  },

  "frxETH-WETH": {
    symbol: "frxETH-WETH",
    name: "frxETH-WETH",
    decimals: 18,
    address: TOKEN_ADDR["frxETH-WETH"],
    logo: "frxETH-WETH",
    displayDecimals: 2,
  },
  "pxETH-stETH": {
    symbol: "pxETH-stETH",
    name: "pxETH-stETH",
    decimals: 18,
    address: TOKEN_ADDR["pxETH-stETH"],
    logo: "pxETH-stETH",
    displayDecimals: 2,
  },
  "pxETH-WETH": {
    symbol: "pxETH-WETH",
    name: "pxETH-WETH",
    decimals: 18,
    address: TOKEN_ADDR["pxETH-WETH"],
    logo: "pxETH-WETH",
    displayDecimals: 2,
  },
  "cbBTC-WBTC": {
    symbol: "cbBTC-WBTC",
    name: "cbBTC-WBTC",
    decimals: 18,
    address: TOKEN_ADDR["cbBTC-WBTC"],
    logo: "cbBTC-WBTC",
    displayDecimals: 2,
  },
  "crvUSD-ETH-CRV": {
    symbol: "crvUSD-ETH-CRV",
    name: "crvUSD-ETH-CRV",
    decimals: 18,
    address: TOKEN_ADDR["crvUSD-ETH-CRV"],
    logo: "crvUSD-ETH-CRV",
    displayDecimals: 2,
  },
  "GHO-cbBTC-WETH": {
    symbol: "GHO-cbBTC-WETH",
    name: "GHO-cbBTC-WETH",
    decimals: 18,
    address: TOKEN_ADDR["GHO-cbBTC-WETH"],
    logo: "GHO-cbBTC-WETH",
    displayDecimals: 2,
  },

  "USDC-WBTC-WETH": {
    symbol: "USDC-WBTC-WETH",
    name: "USDC-WBTC-WETH",
    decimals: 18,
    address: TOKEN_ADDR["USDC-WBTC-WETH"],
    logo: "USDC-WBTC-WETH",
    displayDecimals: 2,
  },

  "USDT-WBTC-WETH": {
    symbol: "USDT-WBTC-WETH",
    name: "USDT-WBTC-WETH",
    decimals: 18,
    address: TOKEN_ADDR["USDT-WBTC-WETH"],
    logo: "USDT-WBTC-WETH",
    displayDecimals: 2,
  },

  "USR-RLP": {
    symbol: "USR-RLP",
    name: "USR-RLP",
    decimals: 18,
    address: TOKEN_ADDR["USR-RLP"],
    logo: "USR-RLP",
    displayDecimals: 2,
  },

  "CVX-ETH": {
    symbol: "CVX-ETH",
    name: "CVX-ETH",
    decimals: 18,
    address: TOKEN_ADDR["CVX-ETH"],
    logo: "CVX-ETH",
    displayDecimals: 2,
  },
  sUSG: {
    symbol: "sUSG",
    name: "sUSG",
    decimals: 18,
    address: TOKEN_ADDR.sUSG,
    logo: "sUSG",
    displayDecimals: 2,
  },
  USG: {
    symbol: "USG",
    name: "USG",
    decimals: 18,
    address: TOKEN_ADDR.USG,
    logo: "USG",
    displayDecimals: 2,
  },
  tgUSD: {
    symbol: "tgUSD",
    name: "tgUSD",
    decimals: 18,
    address: TOKEN_ADDR.tgUSD,
    logo: "tgUSD",
    displayDecimals: 2,
  },
  sgUSD: {
    symbol: "sgUSD",
    name: "sgUSD",
    decimals: 18,
    address: TOKEN_ADDR.sgUSD,
    logo: "sgUSD",
    displayDecimals: 2,
  },
  wcrvUSD: {
    symbol: "wcrvUSD",
    name: "wcrvUSD",
    decimals: 18,
    address: TOKEN_ADDR["wcrvUSD"],
    logo: "wcrvUSD",
    displayDecimals: 2,
  },
  scrvUSD: {
    symbol: "scrvUSD",
    name: "scrvUSD",
    decimals: 18,
    address: TOKEN_ADDR["scrvUSD"],

    logo: "scrvUSD",
    displayDecimals: 2,
  },
  crvUSD: {
    symbol: "crvUSD",
    name: "crvUSD",
    decimals: 18,
    address: TOKEN_ADDR["crvUSD"],
    logo: "crvUSD",
    displayDecimals: 2,
  },
  sTAN: {
    symbol: "sTAN",
    name: "sTAN",
    decimals: 18,
    address: TOKEN_ADDR["sTAN"],
    logo: "sTAN",
    displayDecimals: 2,
  },
  TAN: {
    symbol: "TAN",
    name: "TAN",
    decimals: 18,
    address: TOKEN_ADDR["TAN"],
    logo: "TAN",
    displayDecimals: 2,
  },
}
