import type { Metadata } from "next"
import "./../globals.css"
import Menu, { MenuLink } from "@/components/design_system/structure/menu"
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export const links: MenuLink[] = [
  { href: "/design_system", label: "Home" },
  { href: "/design_system/list", label: "List" },
  { href: "/design_system/layout", label: "Layout" },
  { href: "/design_system/tabs", label: "Tabs" },
  { href: "/design_system/form", label: "Form" },
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <div className="flex content-center">
        <Menu links={links} />
      </div>
      <div>{children}</div>
    </>
  )
}
