import type { Metadata } from "next"
import "@/css_globals.css"
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preload" href="/fonts/RoobertTRIALVF.ttf" as="font" type="font/ttf" crossOrigin="anonymous" />
      </head>
      <body className="dark relative bg-[#070707] antialiased" id="body" suppressHydrationWarning>
        <main className="mx-auto min-h-[80vh] w-full font-gilroy">{children}</main>
      </body>
    </html>
  )
}
