import type { Metadata } from "next"
import "@/css_globals.css"
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

import localFont from "next/font/local"

export const brand = localFont({
  variable: "--font-brand",
  display: "swap",
  src: [
    { path: "../../public/fonts/Gilroy-Regular.woff2", weight: "400", style: "normal" },
    { path: "../../public/fonts/Gilroy-Semibold.woff2", weight: "650", style: "normal" },
  ],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preload" href="/fonts/Gilroy-Regular.woff2" as="font" type="font/woff2" crossOrigin="anonymous" />
      </head>
      <body className={`antialiased" dark relative bg-[#070707] font-gilroy ${brand.variable}`} id="body" suppressHydrationWarning>
        <main className="mx-auto min-h-[80vh] w-full">{children}</main>
      </body>
    </html>
  )
}
