import type { UserDashboardData } from "./dashboard_user_type"

// Fake data for the design and demos (NEXT_PUBLIC_USER_DASHBOARD_MOCK=true). Only the positions and a few real-looking
// earnings are given: the totals and the allocation are derived from the positions, like with the real data.
export const MOCK_USER_DASHBOARD: UserDashboardData = {
  address: "0x8985f1c2d3e4a5b6c7d8e9f0a1b2c3d4e5f69af8",
  usgPrice: 0.99523,
  borrowPositions: [
    {
      marketAddress: "0x4742a56668fbacbc11087f516c4b01ebc48f716f",
      name: "PYUSD-USDC",
      logoKey: "PYUSD-USDC",
      rewardTokens: ["CRV"],
      rewardToken: "CRV",
      marketKind: "HEC",
      depositedUsd: 25_000,
      debt: 13_000,
      health: 1.63,
      claimableUsd: 2_500,
      claimableRewards: [{ token: "CRV", usd: 2_500 }],
      apr: { current: 60.5, projected: 70.2 },
      currentAPRDetails: { APY: 4.2, CRV: 56.3 },
      projectedAPRDetails: { APY: 4.2, CRV: 66 },
      borrowRate: 0,
      liquidationThreshold: 0.85,
      pricing: { priceThreshold: 0.995, minPrice: 0.9887, maxRate: 12.5, minRate: 0 },
    },
    {
      marketAddress: "0xbffbd9c9ac1645285d017a69885304831e8b9b71",
      name: "RLUSD-USDC",
      logoKey: "RLUSD-USDC",
      rewardTokens: ["CRV"],
      rewardToken: "CRV",
      marketKind: "LEC",
      depositedUsd: 12_000,
      debt: 6_000,
      health: 1.7,
      claimableUsd: 640.25,
      claimableRewards: [{ token: "CRV", usd: 640.25 }],
      apr: { current: 9.4, projected: 10.1 },
      currentAPRDetails: { APY: 5.1, CRV: 4.3 },
      projectedAPRDetails: { APY: 5.1, CRV: 5 },
      borrowRate: 4.8,
      liquidationThreshold: 0.9,
      pricing: { priceThreshold: 0.995, minPrice: 0.9887, maxRate: 14, minRate: 2 },
    },
    {
      marketAddress: "0xd2c7257efe28a1b1446904a371e3d51e1c2f7e0e",
      name: "frxUSD-sUSDS",
      logoKey: "frxUSD-sUSDS",
      rewardTokens: ["CRV", "SDT"],
      rewardToken: "SDT",
      marketKind: "HEC",
      depositedUsd: 8_500,
      debt: 0,
      health: null,
      claimableUsd: 120,
      claimableRewards: [
        { token: "CRV", usd: 70 },
        { token: "SDT", usd: 50 },
      ],
      apr: { current: 18.2, projected: 19 },
      currentAPRDetails: { APY: 6.5, SDT: 11.7 },
      projectedAPRDetails: { APY: 6.5, SDT: 12.5 },
      borrowRate: 0,
      liquidationThreshold: 0.88,
      pricing: { priceThreshold: 0.995, minPrice: 0.9887, maxRate: 12.5, minRate: 0 },
    },
    {
      marketAddress: "0x849cf82e0ebcfeab8270cc5a3ea3b26cd481b754",
      name: "USDC-fxUSD",
      logoKey: "USDC-fxUSD",
      rewardTokens: ["CRV", "CVX", "FXN"],
      rewardToken: "FXN",
      marketKind: "FIR",
      depositedUsd: 4_500,
      debt: 2_800,
      health: 1.22,
      claimableUsd: 88.4,
      claimableRewards: [
        { token: "CRV", usd: 30.4 },
        { token: "CVX", usd: 20 },
        { token: "FXN", usd: 38 },
      ],
      apr: { current: 14.6, projected: 14.6 },
      currentAPRDetails: { APY: 3.1, FXN: 11.5 },
      projectedAPRDetails: { APY: 3.1, FXN: 11.5 },
      borrowRate: 6,
      liquidationThreshold: 0.85,
      pricing: { priceThreshold: 0.995, minPrice: 0.9887, maxRate: 6, minRate: 6 },
    },
  ],
  curveLPPositions: [
    {
      key: "0x97ba10115da528c113462ede9c20d7adc806d93f",
      name: "USG-USDC",
      logoKey: "USG-USDC",
      rewardTokens: ["CRV"],
      rewardToken: "CRV",
      apr: { current: 12.4, projected: 13.1 },
      currentAPRDetails: { APY: 2.1, CRV: 10.3 },
      projectedAPRDetails: { APY: 2.1, CRV: 11 },
      depositedUsd: 18_000,
      claimableUsd: 310.5,
      claimUrl: "https://www.curve.finance/dex/ethereum/pools/",
    },
    {
      key: "0xefc056790bb19702b2164ec6ea6ba3ae01d81195",
      name: "USG-frxUSD",
      logoKey: "USG-frxUSD",
      rewardTokens: ["CRV"],
      rewardToken: "CRV",
      apr: { current: 9.8, projected: 10.4 },
      currentAPRDetails: { APY: 1.9, CRV: 7.9 },
      projectedAPRDetails: { APY: 1.9, CRV: 8.5 },
      depositedUsd: 7_500,
      claimableUsd: 96.2,
      claimUrl: "https://www.curve.finance/dex/ethereum/pools/",
    },
  ],
  susgPosition: { apy: 7.4, amount: 25_400, depositedUsd: 26_850, balanceUsd: 26_850 },
  // Per day, consistent with the positions above (deposit x APR / 365). With the detail shown in the tooltips.
  earnings: [
    {
      key: "borrow-market",
      label: "Borrow Market",
      amount: 49.32,
      details: [
        { token: "CRV", amount: 60, usd: 27 },
        { token: "SDT", amount: 90, usd: 22.32 },
      ],
    },
    { key: "curve-lps", label: "Curve LPs Staked", amount: 8.13, details: [{ token: "CRV", amount: 16, usd: 8.13 }] },
    { key: "susg", label: "sUSG", amount: 5.44, details: [{ token: "sUSG", amount: 5.15, usd: 5.44 }] },
  ],
}
